services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=test'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
  redis:
    image: 'redis/redis-stack:latest'
    labels:
      - "org.springframework.boot.service-connection=redis"
    ports:
      - '6379:6379'
